version: "3"
services:
  web:
    build: "./web"
    ports:
      - "5000:5000"
    links:
      - my_db
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@my_db:27017/
      - JWT_SECRET=${JWT_SECRET}
  my_db:
    image: mongo:4.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}